import './global.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Ably & Next.js fundamentals kit',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-row bg-white">{children}</div>
      </body>
    </html>
  );
}
